name: Prompt Injection Scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner CLI (fail on medium)
        run: |
          python -m src.cli --html "<div><input><div class='ai-output'>AI reply</div></div>" --fail-on medium
